apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
   name: cloudshoplite-cluster
   region: us-east-1

nodeGroups:
   - name: ng-1
     instanceType: t3.medium
     desiredCapacity: 2
     minSize: 2
     maxSize: 3
     volumeSize: 20
     ssh:
         allow: false
         

iam:
   withOIDC: true